CREATE TABLE IF NOT EXISTS shows (
    show_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP,
    location TEXT NOT NULL,
    venue TEXT NOT NULL,
    venue_address TEXT NOT NULL,
    support_bands TEXT NOT NULL,
    load_in TEXT NOT NULL,
    load_out TEXT NOT NULL,
    set_time TEXT NOT NULL,
    guarantee TEXT NOT NULL,
    fb_event_link TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tours (
    tour_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTIY, 
    tour_name TEXT NOT NULL, 
    start_date, 
    end_date, 
    country,
    support_bands,
    fb_event_link
)